### ISSUE TITLE
Broken dependencies

### ISSUE THREAD

**Issue by dan-perron** [shibulijack-fd/grunt-aws-s3-website-config#2]
Dependencies should be in a "dependencies" block, not a "devDependencies" block. "devDependencies" are not installed when the module is installed.

**Comment by shibulijack-fd** [comment]
Fixed.

#https://github.com/shibulijack-fd/grunt-aws-s3-website-config/commit/8abc5dd051dab93c901dbfd881a892720d1a51d4

**Comment by dan-perron** [comment]
thanks! any chance you could push a new version to npm?

**Comment by shibulijack-fd** [comment]
Aaand published! Thanks for pointing it out!

**Comment by dan-perron** [comment]
Thanks again!
